on:
  push:
  pull_request:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: Ajithkumarparthasarathy/automate-release-action@master
        with:
          bump_version_scheme: minor
