on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: Ajithkumarparthasarathy/automate-release-action@main
        with:
          bump_version_scheme: minor
          use_github_release_notes: true
          tag_prefix: "A"
